import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Get Supabase credentials from environment variables
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

# Create a Supabase client
supabase: Client = create_client(url, key)

def check_wishlist_table():
    """Check if the wishlist table exists and create it if it doesn't."""
    try:
        # Try to query the wishlist table
        result = supabase.table('wishlist').select("*").limit(1).execute()
        print("Wishlist table exists and is accessible.")
        return True
    except Exception as e:
        print(f"Error accessing wishlist table: {e}")
        print("Attempting to create the wishlist table...")
        
        try:
            # Create the wishlist table
            create_table_sql = """
            CREATE TABLE IF NOT EXISTS wishlist (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL,
                product_id INT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                UNIQUE (user_id, product_id)
            );
            """
            
            # Execute the SQL to create the table
            result = supabase.rpc('execute_sql', {'query': create_table_sql}).execute()
            print("Wishlist table created successfully!")
            return True
            
        except Exception as create_error:
            print(f"Failed to create wishlist table: {create_error}")
            return False

if __name__ == "__main__":
    print("Checking wishlist table...")
    success = check_wishlist_table()
    if success:
        print("Wishlist table check completed successfully!")
    else:
        print("Failed to set up wishlist table. Please check the error messages above.")
