import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Get Supabase credentials from environment variables
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

# Create a Supabase client
supabase: Client = create_client(url, key)

def create_wishlist_table():
    """Creates the wishlist table and sets up RLS policies."""
    
    # SQL statement to create the wishlist table
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS wishlist (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
        product_id INT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE (user_id, product_id)
    );
    """

    # SQL statements to enable RLS and create policies
    rls_policies_sql = """
    -- Enable RLS on the wishlist table
    ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

    -- Policy: Users can view their own wishlist items
    CREATE POLICY "select_own_wishlist_items"
    ON public.wishlist FOR SELECT
    USING (auth.uid() = user_id);

    -- Policy: Users can add items to their own wishlist
    CREATE POLICY "insert_own_wishlist_items"
    ON public.wishlist FOR INSERT
    WITH CHECK (auth.uid() = user_id);

    -- Policy: Users can remove items from their own wishlist
    CREATE POLICY "delete_own_wishlist_items"
    ON public.wishlist FOR DELETE
    USING (auth.uid() = user_id);
    """

    full_sql = f"{create_table_sql}\n{rls_policies_sql}"

    print("\n--- SQL to be executed ---")
    print(full_sql)
    print("--------------------------\n")

    try:
        # Execute the SQL statements
        response = supabase.rpc('execute_sql', {"sql": full_sql}).execute()
        
        # Check for errors in the response
        if response.get('error'):
            print(f"Error creating wishlist table: {response['error']['message']}")
        else:
            print("Wishlist table and RLS policies created successfully!")
            print("You can now manage wishlists in your application.")

    except Exception as e:
        print(f"An error occurred: {e}")
        print("\nPlease copy the SQL above and run it manually in your Supabase SQL Editor.")

if __name__ == "__main__":
    create_wishlist_table()
