print("""
Please execute the following SQL in your Supabase SQL Editor to create the wishlist table:

-- Create the wishlist table
CREATE TABLE IF NOT EXISTS wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    product_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, product_id)
);

-- Enable Row Level Security
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
CREATE POLICY "Users can view their own wishlist items" 
ON wishlist FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can add to their own wishlist"
ON wishlist FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can remove from their own wishlist"
ON wishlist FOR DELETE
USING (auth.uid() = user_id);

After executing the above SQL, the wishlist functionality will be ready to use.
""")
