import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Get Supabase credentials from environment variables
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_ANON_KEY")

# Create a Supabase client
supabase: Client = create_client(url, key)

def setup_wishlist_table():
    """Create the wishlist table in Supabase if it doesn't exist"""
    try:
        # SQL to create the wishlist table
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS wishlist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL,
            product_id INTEGER NOT NULL,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE(user_id, product_id)
        );
        """
        
        # Execute the SQL to create the table
        result = supabase.rpc('execute_sql', {'query': create_table_sql}).execute()
        
        # Check if the table was created successfully
        if hasattr(result, 'data'):
            print("✅ Wishlist table created successfully!")
            return True
        else:
            print("❌ Failed to create wishlist table.")
            return False
            
    except Exception as e:
        print(f"❌ Error creating wishlist table: {str(e)}")
        return False

if __name__ == "__main__":
    print("Setting up Supabase wishlist table...")
    if setup_wishlist_table():
        print("✅ Setup completed successfully!")
    else:
        print("❌ Setup failed. Please check the error messages above.")
